# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('sex', models.BinaryField(choices=[(True, '女'), (False, '男')], default=True, verbose_name='性别')),
                ('address', models.CharField(max_length=200, verbose_name='住址')),
                ('profession', models.CharField(max_length=32, verbose_name='职业')),
                ('anaphylaxis', models.CharField(max_length=200, verbose_name='药物过敏史')),
                ('first_visit_date', models.DateField(verbose_name='初诊日期')),
                ('symptom', models.CharField(max_length=200, verbose_name='症状')),
                ('diagnosis', models.CharField(max_length=200, verbose_name='诊断')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonetype', models.CharField(max_length=10, verbose_name='类型')),
                ('number', models.PositiveIntegerField(verbose_name='电话号码')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mypats.Patient')),
            ],
        ),
    ]
