# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[(True, '女'), (False, '男')], default='女', max_length=2, verbose_name='性别'),
        ),
    ]
