# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 02:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypats', '0002_auto_20170608_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='anaphylaxis',
            field=models.CharField(blank=True, max_length=200, verbose_name='药物过敏史'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=200, verbose_name='诊断'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_visit_date',
            field=models.DateField(default=datetime.date.today, verbose_name='初诊日期'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=32, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('女', '女'), ('男', '男')], default='男', max_length=2, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptom',
            field=models.CharField(blank=True, max_length=200, verbose_name='症状'),
        ),
    ]
