# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypats', '0004_auto_20170609_1504'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': '患者', 'verbose_name_plural': '患者'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='anaphylaxis',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='药物过敏史'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='诊断'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profession',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='职业'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='symptom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='症状'),
        ),
    ]
